/////////////////////////////////////////////////////////////////////////////////////////
//
// Please refer to "COPYRIGHT.md" for the relevant copyright statement of this software.
//
/////////////////////////////////////////////////////////////////////////////////////////
//
#pragma once
#include "../../inc/GcTcUiCatalogView.h"
#include "AcTcUI.h"
#include "AcTcUiCatalogViewItem.h"
#define AcTcCatalogItemArray  GcTcCatalogItemArray
#define ACTCUI_IDW_CATALOGVIEW  GCTCUI_IDW_CATALOGVIEW
#define ACTCUI_CVSTYLE_SHOWTEXT  GCTCUI_CVSTYLE_SHOWTEXT
#define ACTCUI_CVSTYLE_SAVE_ORDER_IN_CATALOG  GCTCUI_CVSTYLE_SAVE_ORDER_IN_CATALOG
#define ACTCUI_CVSTYLE_NO_QSL  GCTCUI_CVSTYLE_NO_QSL
#define ACTCUI_CVSTYLE_NO_SELECTION  GCTCUI_CVSTYLE_NO_SELECTION
#define ACTCUI_CVSTYLE_NO_VIEW_BUTTON  GCTCUI_CVSTYLE_NO_VIEW_BUTTON
#define ACTCUI_CVSTYLE_LISTVIEW  GCTCUI_CVSTYLE_LISTVIEW
#define ACTCUI_CVSTYLE_TOOLTIPS  GCTCUI_CVSTYLE_TOOLTIPS
#define ACTCUI_CVSTYLE_MULTISELECT  GCTCUI_CVSTYLE_MULTISELECT
#define ACTCUI_CVSTYLE_EDITLABELS  GCTCUI_CVSTYLE_EDITLABELS
#define ACTCUI_CVSTYLE_HOVERSELECT  GCTCUI_CVSTYLE_HOVERSELECT
#define ACTCUI_CVSTYLE_NO_DRAGDROP  GCTCUI_CVSTYLE_NO_DRAGDROP
#define ACTCUI_CVSTYLE_NO_CUT  GCTCUI_CVSTYLE_NO_CUT
#define ACTCUI_CVSTYLE_NO_COPY  GCTCUI_CVSTYLE_NO_COPY
#define ACTCUI_CVSTYLE_NO_PASTE  GCTCUI_CVSTYLE_NO_PASTE
#define ACTCUI_CVSTYLE_NO_REFRESH  GCTCUI_CVSTYLE_NO_REFRESH
#define ACTCUI_CVSTYLE_NO_REMOVE  GCTCUI_CVSTYLE_NO_REMOVE
#define ACTCUI_CVSTYLE_NO_RENAME  GCTCUI_CVSTYLE_NO_RENAME
#define ACTCUI_CVSTYLE_NO_PROPERTIES  GCTCUI_CVSTYLE_NO_PROPERTIES
#define ACTCUI_CVSTYLE_NO_HELP  GCTCUI_CVSTYLE_NO_HELP
#define ACTCUI_CVSTYLE_NO_VIEWOPTIONS  GCTCUI_CVSTYLE_NO_VIEWOPTIONS
#define ACTCUI_CVSTYLE_NO_OPERATIONS  GCTCUI_CVSTYLE_NO_OPERATIONS
#define ACTCUI_CVSTYLE_NO_COPY  GCTCUI_CVSTYLE_NO_COPY
#define ACTCUI_CVSTYLE_NO_PASTE  GCTCUI_CVSTYLE_NO_PASTE
#define ACTCUI_CVSTYLE_NO_REFRESH  GCTCUI_CVSTYLE_NO_REFRESH
#define ACTCUI_CVSTYLE_NO_REMOVE  GCTCUI_CVSTYLE_NO_REMOVE
#define ACTCUI_CVSTYLE_NO_RENAME  GCTCUI_CVSTYLE_NO_RENAME
#define ACTCUI_CVSTYLE_NO_PROPERTIES  GCTCUI_CVSTYLE_NO_PROPERTIES
#define ACTCUI_CVSTYLE_NO_HELP  GCTCUI_CVSTYLE_NO_HELP
#define ACTCUI_CVSTYLE_NO_VIEWOPTIONS  GCTCUI_CVSTYLE_NO_VIEWOPTIONS
#define ACTCUI_CVSTYLE_NO_FLYOUT  GCTCUI_CVSTYLE_NO_FLYOUT
#define ACTCUI_CVSTYLE_NO_SCROLLBAR  GCTCUI_CVSTYLE_NO_SCROLLBAR
#define ACTCUI_DDO_ACCEPT_TOOL  GCTCUI_DDO_ACCEPT_TOOL
#define ACTCUI_DDO_ACCEPT_PALETTE  GCTCUI_DDO_ACCEPT_PALETTE
#define ACTCUI_DDO_ACCEPT_PACKAGE  GCTCUI_DDO_ACCEPT_PACKAGE
#define ACTCUI_DDO_ACCEPT_CATEGORY  GCTCUI_DDO_ACCEPT_CATEGORY
#define ACTCUI_DDO_ACCEPT_CATALOG  GCTCUI_DDO_ACCEPT_CATALOG
#define ACTCUI_DDO_ACCEPT_STOCKTOOL  GCTCUI_DDO_ACCEPT_STOCKTOOL
#define ACTCUI_DDO_ACCEPT_FILES  GCTCUI_DDO_ACCEPT_FILES
#define ACTCUI_DDO_ACCEPT_ALL_ITEMS  GCTCUI_DDO_ACCEPT_ALL_ITEMS
#define ACTCUI_DDO_ACCEPT_STOCKTOOL  GCTCUI_DDO_ACCEPT_STOCKTOOL
#define ACTCUI_DDO_ACCEPT_PALETTE  GCTCUI_DDO_ACCEPT_PALETTE
#define ACTCUI_DDO_ACCEPT_PACKAGE  GCTCUI_DDO_ACCEPT_PACKAGE
#define ACTCUI_DDO_ACCEPT_CATEGORY  GCTCUI_DDO_ACCEPT_CATEGORY
#define ACTCUI_DDO_ACCEPT_CATALOG  GCTCUI_DDO_ACCEPT_CATALOG
#define ACTCUI_DDO_ACCEPT_FILES  GCTCUI_DDO_ACCEPT_FILES
#define ACTCUI_CVHT_NOWHERE  GCTCUI_CVHT_NOWHERE
#define ACTCUI_CVHT_ITEM  GCTCUI_CVHT_ITEM
#define ACTCUI_CVHT_ITEMIMAGE  GCTCUI_CVHT_ITEMIMAGE
#define ACTCUI_CVHT_ITEMLABEL  GCTCUI_CVHT_ITEMLABEL
#define ACTCUI_CVHT_BACKGROUND  GCTCUI_CVHT_BACKGROUND
#define ACTCUI_CVHT_ABOVE  GCTCUI_CVHT_ABOVE
#define ACTCUI_CVHT_BELOW  GCTCUI_CVHT_BELOW
#define ACTCUI_CVHT_LEFT  GCTCUI_CVHT_LEFT
#define ACTCUI_CVHT_RIGHT  GCTCUI_CVHT_RIGHT
#define ACTCUI_CVHT_ITEMTRIGGER  GCTCUI_CVHT_ITEMTRIGGER
#define ACTCUI_OVERLAY_ALIGN_TOPLEFT  GCTCUI_OVERLAY_ALIGN_TOPLEFT
#define ACTCUI_OVERLAY_ALIGN_TOPRIGHT  GCTCUI_OVERLAY_ALIGN_TOPRIGHT
#define ACTCUI_OVERLAY_ALIGN_BOTTOMLEFT  GCTCUI_OVERLAY_ALIGN_BOTTOMLEFT
#define ACTCUI_OVERLAY_ALIGN_BOTTOMRIGHT  GCTCUI_OVERLAY_ALIGN_BOTTOMRIGHT
#define CAcTcUiCatalogView  CGcTcUiCatalogView
#define CAcTcUiScheme CGcTcUiScheme
#define AcTcUiSystemInternals       GcTcUiSystemInternals
#define AcTcCatalogItem  GcTcCatalogItem

#define OnBeginAcadDrop    OnBeginGcadDrop
#define OnEndAcadDrop      OnEndGcadDrop