/////////////////////////////////////////////////////////////////////////////////////////
//
// Please refer to "COPYRIGHT.md" for the relevant copyright statement of this software.
//
/////////////////////////////////////////////////////////////////////////////////////////
//
#pragma once
#include "../../inc/gxboiler.h"
#include "adesk.h"  
#include "axobjref.h"

#define IAcadBaseObject IGcadBaseObject
#define IAcadBaseObject2 IGcadBaseObject2
#define IAcadAcCmColor IGcadGcCmColor
#define IAcadBaseDatabase IGcadBaseDatabase
#define IAcadAcCmColorAccess IGcadGcCmColorAccess
#define IAcadBaseSubEntity IGcadBaseSubEntity
#define LPACADGCCMCOLORACCESS LPGCADGCCMCOLORACCESS
#define LPACADSUBENTITY LPGCADSUBENTITY
#define LPACADBASEDATABASE LPGCADBASEDATABASE
#define AcAxErase GcAxErase
#define AcAxSetXData GcAxSetXData
#define AcAxGetXData GcAxGetXData
#define AcAxGetObjectName GcAxGetObjectName
#define AcAxGetHandle GcAxGetHandle
#define AcAxGetColor GcAxGetColor
#define AcAxPutColor GcAxPutColor
#define AcAxGetTrueColor GcAxGetTrueColor
#define AcAxPutTrueColor GcAxPutTrueColor
#define AcAxGetLayer GcAxGetLayer
#define AcAxPutLayer GcAxPutLayer
#define AcAxGetLinetype GcAxGetLinetype
#define AcAxPutLinetype GcAxPutLinetype
#define AcAxGetTransparency GcAxGetTransparency
#define AcAxPutTransparency GcAxPutTransparency
#define AcAxGetShadowDisplay GcAxGetShadowDisplay
#define AcAxPutShadowDisplay GcAxPutShadowDisplay
#define AcAxEnableShadowDisplay GcAxEnableShadowDisplay
#define AcAxGetMaterial GcAxGetMaterial
#define AcAxPutMaterial GcAxPutMaterial
#define AcAxGetLinetypeScale GcAxGetLinetypeScale
#define AcAxPutLinetypeScale GcAxPutLinetypeScale
#define AcAxGetVisible GcAxGetVisible
#define AcAxPutVisible GcAxPutVisible
#define AcAxArrayPolar GcAxArrayPolar
#define AcAxArrayRectangular GcAxArrayRectangular
#define AcAxHighlight GcAxHighlight
#define AcAxCopy GcAxCopy
#define AcAxMove GcAxMove
#define AcAxRotate GcAxRotate
#define AcAxRotate3D GcAxRotate3D
#define AcAxMirror GcAxMirror
#define AcAxMirror3D GcAxMirror3D
#define AcAxScaleEntity GcAxScaleEntity
#define AcAxTransformBy GcAxTransformBy
#define AcAxUpdate GcAxUpdate
#define AcAxGetBoundingBox GcAxGetBoundingBox
#define AcAxIntersectWith GcAxIntersectWith
#define AcAxGetPlotStyleName GcAxGetPlotStyleName
#define AcAxPutPlotStyleName GcAxPutPlotStyleName
#define AcAxGetLineWeight GcAxGetLineWeight
#define AcAxPutLineWeight GcAxPutLineWeight
#define AcAxGetHyperlinks GcAxGetHyperlinks
#define AcAxHasExtensionDictionary GcAxHasExtensionDictionary
#define AcAxGetExtensionDictionary GcAxGetExtensionDictionary
#define AcAxGetDatabase GcAxGetDatabase
#define AcAxGetOwnerId GcAxGetOwnerId
#define AcAxGetObjectId32 GcAxGetObjectId32
#define AcAxGetObjectId64 GcAxGetObjectId64
#define AaiseAcAXException RaiseGcAXException
#define AaiseArxException RaiseGrxException
#define AcAxGetIUnknownOfObject GcAxGetIUnknownOfObject
#define AcAxGetIUnknownOfObject GcAxGetIUnknownOfObject
#define AcAxErase GcAxErase
#define AcAxSetXData GcAxSetXData
#define AcAxGetXData GcAxGetXData
#define AcAxGetObjectName GcAxGetObjectName
#define AcAxGetHandle GcAxGetHandle
#define AcAxGetColor GcAxGetColor
#define AcAxPutColor GcAxPutColor
#define AcAxGetTrueColor GcAxGetTrueColor
#define AcAxPutTrueColor GcAxPutTrueColor
#define AcAxGetLayer GcAxGetLayer
#define AcAxPutLayer GcAxPutLayer
#define AcAxGetLinetype GcAxGetLinetype
#define AcAxPutLinetype GcAxPutLinetype
#define AcAxGetTransparency GcAxGetTransparency
#define AcAxPutTransparency GcAxPutTransparency
#define AcAxGetMaterial GcAxGetMaterial
#define AcAxPutMaterial GcAxPutMaterial
#define AcAxGetLinetypeScale GcAxGetLinetypeScale
#define AcAxPutLinetypeScale GcAxPutLinetypeScale
#define AcAxGetShadowDisplay GcAxGetShadowDisplay
#define AcAxPutShadowDisplay GcAxPutShadowDisplay
#define AcAxEnableShadowDisplay GcAxEnableShadowDisplay
#define AcAxGetVisible GcAxGetVisible
#define AcAxPutVisible GcAxPutVisible
#define AcAxArrayPolar GcAxArrayPolar
#define AcAxArrayRectangular GcAxArrayRectangular
#define AcAxHighlight GcAxHighlight
#define AcAxCopy GcAxCopy
#define AcAxMove GcAxMove
#define AcAxRotate GcAxRotate
#define AcAxRotate3D GcAxRotate3D
#define AcAxMirror GcAxMirror
#define AcAxMirror3D GcAxMirror3D
#define AcAxScaleEntity GcAxScaleEntity
#define AcAxTransformBy GcAxTransformBy
#define AcAxUpdate GcAxUpdate
#define AcAxGetBoundingBox GcAxGetBoundingBox
#define AcAxIntersectWith GcAxIntersectWith
#define AcAxGetPlotStyleName GcAxGetPlotStyleName
#define AcAxPutPlotStyleName GcAxPutPlotStyleName
#define AcAxGetLineWeight GcAxGetLineWeight
#define AcAxPutLineWeight GcAxPutLineWeight
#define AcAxGetHyperlinks GcAxGetHyperlinks
#define AcAxHasExtensionDictionary GcAxHasExtensionDictionary
#define AcAxGetExtensionDictionary GcAxGetExtensionDictionary
#define AcAxGetOwnerId GcAxGetOwnerId
#define AcAxGet_UIsolineDensity GcAxGet_UIsolineDensity
#define AcAxPut_UIsolineDensity GcAxPut_UIsolineDensity
#define AcAxGet_VIsolineDensity GcAxGet_VIsolineDensity
#define AcAxPut_VIsolineDensity GcAxPut_VIsolineDensity
#define AcAxGet_WireframeType GcAxGet_WireframeType
#define AcAxPut_WireframeType GcAxPut_WireframeType
#define AcAxGetMaintainAssociativity GcAxGetMaintainAssociativity
#define AcAxPutMaintainAssociativity GcAxPutMaintainAssociativity
#define AcAxGetShowAssociativity GcAxGetShowAssociativity
#define AcAxPutShowAssociativity GcAxPutShowAssociativity
#define AcAxGetEdgeExtensionDistances GcAxGetEdgeExtensionDistances
#define AcAxPutEdgeExtensionDistances GcAxPutEdgeExtensionDistances
#define AcAxGetSurfTrimAssociativity GcAxGetSurfTrimAssociativity
#define AcAxPutSurfTrimAssociativity GcAxPutSurfTrimAssociativity
