#pragma once

#define _ARXCOMMAND_ENTRY _GRXCOMMAND_ENTRY
#define _ADSSYMBOL_ENTRY  _GDSSYMBOL_ENTRY 

#define ACED_ARXCOMMAND_ENTRY_AUTO      GCED_GRXCOMMAND_ENTRY_AUTO
#define ACED_ARXCOMMAND_ENTRYBYID_AUTO  GCED_GRXCOMMAND_ENTRYBYID_AUTO
#define ACED_ADSSYMBOL_ENTRY_AUTO       GCED_GDSSYMBOL_ENTRY_AUTO
#define ACED_ADSCOMMAND_ENTRY_AUTO      GCED_GDSCOMMAND_ENTRY_AUTO
#define ACED_ADSSYMBOL_ENTRYBYID_AUTO   GCED_GDSSYMBOL_ENTRYBYID_AUTO
#define ACED_ADSCOMMAND_ENTRYBYID_AUTO  GCED_GDSCOMMAND_ENTRYBYID_AUTO

#define ARXCOMMAND_FIRST_ENTRYNAME       GRXCOMMAND_FIRST_ENTRYNAME
#define ARXCOMMAND_LAST_ENTRYNAME        GRXCOMMAND_LAST_ENTRYNAME
#define ACED_ARXCOMMAND_ENTRY_PRAGMA     GCED_GRXCOMMAND_ENTRY_PRAGMA
#define ADSSYMBOL_FIRST_ENTRYNAME        GDSSYMBOL_FIRST_ENTRYNAME
#define ADSSYMBOL_LAST_ENTRYNAME         GDSSYMBOL_LAST_ENTRYNAME
#define ACED_ADSSYMBOL_ENTRY_PRAGMA      GCED_GDSSYMBOL_ENTRY_PRAGMA

#define AcRxArxApp GcRxArxApp

#include "accmd.h"
#include "ads.h"
#include "dbxEntryPoint.h"
#ifdef __ATLCOM_H__
#include "dynpropmgr.h"
#endif
#include "../grx/grxEntryPoint.h"